rocketmq:
  producer:
    # ??????????????group?????,????????rocketmq???ip@pid(pid??jvm??)??????
    groupName: vehicleProducerGroup
    #mq?nameserver??
    namesrvAddr: 101.34.23.190:9876
    #???????jvm????producer????mq??????????????instanceName
    instanceName: vehicleProducer
    #topic??
    topic: TEST
    #???????????tag
    tag: TEST
    #??????
    maxMessageSize: 131072 # 1024*128
    #????????
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: 101.34.23.190:9876
    groupName: vehicleProducerGroup
    topic: sms
    tag: verifycode
    consumeThreadMin: 20
    consumeThreadMax: 64
