spring:
  # 服务名称
  application:
    name: rabbitmq-delayed
  datasource:
    url: jdbc:mysql://60.205.221.238:3306/t_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: '!liu7751541'
    driver-class-name: com.mysql.cj.jdbc.Driver
  # RabbitMQ配置
  rabbitmq:
    # 开启发布者确认模式
    publisher-confirm-type: correlated
    #publisher-returns: true    # 开启发送端消息抵达队列的确认
    host: 60.205.221.238
    port: 5672
    username: guest
    password: guest
  template: #只有抵达队列，以异步发送优先回调returnCallback
  mandatory: true
server:
  port: 8882